### ISSUE TITLE
Reopen an issue closed by a PR being merged

### ISSUE THREAD

**Issue by CdrMarks** [TheRecruitLab/issue-bot#1]
User story:
* As a project manager, I would like issues that are closed when a PR is merged to be reopened so that the work can be tracked through future stages until deployed to production.

Acceptance criteria:
* The https://github.com/TheRecruitLab/issue-bot repository, a public repository, is configured as a GitHub Action.
* An action exists to reopen an issue that is closed when a [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) PR is merged.

Notes:
* The repository was created as a public repository in the event that we choose to [publish it in the GitHub Marketplace](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace).
* Documentation:
  * [Creating actions](https://docs.github.com/en/actions/creating-actions)

**Comment by dylanflint07** [comment]
@CdrMarks https://www.loom.com/share/0737a960acac4491a4a7d99953523817?sid=3d8e0ab8-160e-4a61-9ae7-62d6b3f0aa4d

This should be done. Apparently there was no main branch when it started, so it made my feature branch the main branch. So there's no PR, it's the present state of the repository.
