### ISSUE TITLE
Create PR when two branch are not in sync

### ISSUE THREAD

**Issue by CdrMarks** [TheRecruitLab/issue-bot#11]
User Story

As a developer, when I merge a new PR to dev, it should create a new PR for dev -> staging if none exists.

As a developer, when I merge a new PR to staging, it should create a new PR for staging -> production if none exists.

As a developer, when I merge dev -> staging, all the issues associated with the PR's commits in the PRs commits should move their status to staging.

As a developer, when I merge staging -> production, all the issues associated with the PR's commits should move their status to production and be closed.

**Acceptance Criteria**
* A PR is created when a non-empty diff can be generated between a source and target branch if a PR doesn't already exist.

**Comment by dylanflint07** [comment]
@CdrMarks Can you see if there is a permission to read commits / create Pull Requests for the issue bot github app? I need to be able to use these endpoints to get the branch comparisons and to create a PR and I'm getting a permission error.

https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#compare-two-commits

https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#create-a-pull-request

```
data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/commits/commits#compare-two-commits',
      status: '403'
    }

    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/pulls/pulls#create-a-pull-request',
      status: '403'
    }
```

**Comment by CdrMarks** [comment]
For https://github.com/organizations/TheRecruitLab/settings/apps/trl-issue-bot/permissions, I have changed this permission to read-only.  ![Image](https://github.com/user-attachments/assets/775ec594-7be6-47a3-9997-f92037e634e5)



When saving, this message was shown to me.
![Image](https://github.com/user-attachments/assets/5f0e0e27-00a7-4914-8f0b-201db9c419a4)



Let me know if this is helpful.

**Comment by dylanflint07** [comment]
I'm still getting the same error. I think it may need adjusted elsewhere as well at the repository level. I can't edit the repo permissions, but this is what it says permission wise is available for The Lab / Landing Page. 
https://github.com/TheRecruitLab/landing-pages/settings/installations
<img width="1086" alt="Screenshot 2024-08-13 at 1 22 58 PM" src="https://github.com/user-attachments/assets/d9e0f08d-588f-45d7-8877-d456eac7e665">

**Comment by dylanflint07** [comment]
@CdrMarks

**Comment by CdrMarks** [comment]
I found that I needed to accept the permission change as well.  Can you check again to see if you have the access you need?

**Comment by dylanflint07** [comment]
@CdrMarks The commit permission works now. It looks like the create pull request permission still isn't set, though.

```
{
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/pulls/pulls#create-a-pull-request',
      status: '403'
    }
```

**Comment by CdrMarks** [comment]
Can you try the PR permission again?
