### ISSUE TITLE
Set an issue's project status when an issue's linked PR is merged

### ISSUE THREAD

**Issue by CdrMarks** [TheRecruitLab/issue-bot#2]
User story:
* As a project manager, I would like the issue status of an issue in a project to be set when a PR is merged so that the work can be tracked through future statuses until deployed to production.

Acceptance criteria:
* The existing action is extended to set the status of an issue when a [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) PR is merged.
* Documentation exists in the repository's README.md to alert users that [built-in workflows for your project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-built-in-automations) may conflict with this action.

![Image](https://github.com/TheRecruitLab/issue-bot/assets/3489003/8c58ed87-d054-4b12-9e1e-4434c06bd200)

Notes:
* The repository was created as a public repository in the event that we choose to [publish it in the GitHub Marketplace](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace).
* 
* Documentation:
  * [Creating actions](https://docs.github.com/en/actions/creating-actions)

**Comment by dylanflint07** [comment]
@CdrMarks I'm having a difficult time querying the project information in order to update the issue's project items. I can't see the settings for the landing_pages repository. Can you see if the repository is linked to the engineering board project?

**Comment by CdrMarks** [comment]
@dylanflint07 I'm not quite sure what to look for.  Is it working differently for the-lab repository?

**Comment by dylanflint07** [comment]
No the settings are hidden from me on both. I can set it on the issue bot repository, but not the others.

<img width="1235" alt="Screenshot 2024-03-12 at 9 51 35 AM" src="https://github.com/TheRecruitLab/issue-bot/assets/64794272/8174596a-8209-4bbd-9371-c97e5d9fbc04">

**Comment by CdrMarks** [comment]
I've given you Admin access on the project.  Let me know if you need anything else.

**Comment by dylanflint07** [comment]
Do you see an option for projects on the lab / landing pages? It's still not showing up for me.

**Comment by CdrMarks** [comment]
Closing the loop on your question from earlier:
> Do you see an option for projects on the lab / landing pages?

We aren't using repository projects.  We're using organization projects.

I did some searching and didn't really find much that was terribly useful.  Hopefully you'll be inspired by one of these:

* I upvoted this: https://github.com/orgs/community/discussions/36691 
* The source link at the end of https://github.com/orgs/community/discussions/19028 looks like someone else running into the same problem you are.
* This draft looks to be limited to a repository project: https://medium.com/@martatatiana/github-projects-change-issue-status-based-on-pull-request-change-45dcacab9fb7.  She hasn't posted on Medium since.
* This also looks like its a repository-specific project.
* This PR says the action supports adding an issue or pull request to a project in the same origination as the issue or pull request.  https://github.com/actions/add-to-project/pull/142

**Comment by CdrMarks** [comment]
Rolled over into Sprint 14.

**Comment by dylanflint07** [comment]
@CdrMarks It looks like we'll need to register the github app under TheRecruitLab, which it looks like you'll need to be an owner of the organization in order to do that.

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions
https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app

**Comment by CdrMarks** [comment]
Note: Dylan and I met this morning to create the app.
