### ISSUE TITLE
Issue closed with reason:"not planned" shouldn't have its status set to Production

### ISSUE THREAD

**Issue by CdrMarks** [TheRecruitLab/issue-bot#7]
**User Story**

As a TRL Engineer, I want GitHub issues closed with reason "not planned" to not be automatically moved to Production since this work was never released to Production.

**Acceptance Criteria**

* An issue closed as not planned does not have its project status automatically updated.

Notes:
* this may required a webhook for the lab and landing pages.

**Comment by CdrMarks** [comment]
Sprint changed from `Sprint 22` to `Sprint 24`

**Comment by dylanflint07** [comment]
@CdrMarks It doesn't look like we automatically update statuses by default anymore when something is closed. It'll retain the current status when closed right now.

**Comment by CdrMarks** [comment]
Are you saying that issue can be closed?

**Comment by dylanflint07** [comment]
Yes. I tried closing issues as unplanned / not unplanned and the status isn't affected. I'm guessing when we made changes to some of the workflows to use the issue-bot it also fixed this issue.

**Comment by dylanflint07** [comment]
@CdrMarks I'm going to go ahead and close this if that's all right with you.
